/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main1.java
 *
 * Created on May 29, 2023, 7:53:51 PM
 */
package GUI;

import BangDiem.frmBangDiem;
import BangDiem.frmTinhDiem;
import GiaoVien.frmGiaoVien;
import Khoa.frmKhoa;
import LopHoc.frmLopHoc;
import MonHoc.frmMonHoc;
import Search.Search;
import SinhVien.frmSinhVien;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.URISyntaxException;
import java.text.DateFormat;
import java.util.Calendar;

import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author dell
 */
public class Main extends javax.swing.JFrame {

    /** Creates new form Main1 */
    public Main() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpContent = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jbInputStudent = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jbInputTeacher = new javax.swing.JButton();
        jbInputDiem = new javax.swing.JButton();
        jbClass = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmHeThong = new javax.swing.JMenu();
        jmiExit = new javax.swing.JMenuItem();
        jmTimKiem = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtpContent.setMinimumSize(new java.awt.Dimension(33, 28));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/banner.png"))); // NOI18N
        jtpContent.addTab("tab1", jLabel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 36));
        jLabel5.setForeground(new java.awt.Color(-65536,true));
        jLabel5.setText("HỆ THỐNG QUẢN LÍ SINH VIÊN ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1164, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 227, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 227, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 11, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        jbInputStudent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbInputStudent.setText("Nhập Sinh Viên");
        jbInputStudent.setDefaultCapable(false);
        jbInputStudent.setHideActionText(true);
        jbInputStudent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbInputStudent.setIconTextGap(10);
        jbInputStudent.setMargin(new java.awt.Insets(1, 14, 2, 14));
        jbInputStudent.setPreferredSize(new java.awt.Dimension(151, 33));
        jbInputStudent.setSelected(true);
        jbInputStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInputStudentActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 204, 102));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MENU");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jbInputTeacher.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbInputTeacher.setText("Nhập Giáo Viên");
        jbInputTeacher.setDefaultCapable(false);
        jbInputTeacher.setHideActionText(true);
        jbInputTeacher.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbInputTeacher.setIconTextGap(10);
        jbInputTeacher.setMargin(new java.awt.Insets(1, 14, 2, 14));
        jbInputTeacher.setPreferredSize(new java.awt.Dimension(151, 33));
        jbInputTeacher.setSelected(true);
        jbInputTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInputTeacherActionPerformed(evt);
            }
        });

        jbInputDiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbInputDiem.setText("Nhập Điểm");
        jbInputDiem.setDefaultCapable(false);
        jbInputDiem.setHideActionText(true);
        jbInputDiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbInputDiem.setIconTextGap(10);
        jbInputDiem.setMargin(new java.awt.Insets(1, 14, 2, 14));
        jbInputDiem.setPreferredSize(new java.awt.Dimension(151, 33));
        jbInputDiem.setSelected(true);
        jbInputDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInputDiemActionPerformed(evt);
            }
        });

        jbClass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbClass.setText("Nhập Lớp");
        jbClass.setDefaultCapable(false);
        jbClass.setHideActionText(true);
        jbClass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbClass.setIconTextGap(10);
        jbClass.setMargin(new java.awt.Insets(1, 14, 2, 14));
        jbClass.setPreferredSize(new java.awt.Dimension(151, 33));
        jbClass.setSelected(true);
        jbClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClassActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Nhập Môn Học");
        jButton5.setDefaultCapable(false);
        jButton5.setHideActionText(true);
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.setIconTextGap(10);
        jButton5.setMargin(new java.awt.Insets(1, 14, 2, 14));
        jButton5.setPreferredSize(new java.awt.Dimension(151, 33));
        jButton5.setSelected(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Nhập Khoa");
        jButton6.setDefaultCapable(false);
        jButton6.setHideActionText(true);
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.setIconTextGap(10);
        jButton6.setMargin(new java.awt.Insets(1, 14, 2, 14));
        jButton6.setPreferredSize(new java.awt.Dimension(151, 33));
        jButton6.setSelected(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jMenuBar2.setBackground(new java.awt.Color(255, 255, 255));

        jmHeThong.setBackground(new java.awt.Color(204, 204, 255));
        jmHeThong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Measure.png"))); // NOI18N
        jmHeThong.setText("Hệ thống           ");
        jmHeThong.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Measure.png"))); // NOI18N

        jmiExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jmiExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        jmiExit.setText(" Exit                     ");
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        jmHeThong.add(jmiExit);

        jMenuBar2.add(jmHeThong);

        jmTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Search-icon.png"))); // NOI18N
        jmTimKiem.setText("Tìm kiếm");
        jmTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmTimKiemMouseClicked(evt);
            }
        });
        jmTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTimKiemActionPerformed(evt);
            }
        });
        jMenuBar2.add(jmTimKiem);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbInputStudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jbInputTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jbInputDiem, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jbClass, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 1168, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtpContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbInputStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbInputTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbInputDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(289, 289, 289)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbInputStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInputStudentActionPerformed
        frmSinhVien sinhVien = new frmSinhVien();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Sinh Viên", sinhVien);
}//GEN-LAST:event_jbInputStudentActionPerformed

private void jbInputTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInputTeacherActionPerformed
        frmGiaoVien giaoVien = new frmGiaoVien();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Giáo Viên", giaoVien);
}//GEN-LAST:event_jbInputTeacherActionPerformed

private void jbInputDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInputDiemActionPerformed
        frmBangDiem bangDiem = new frmBangDiem();
        jtpContent.removeAll();
        jtpContent.add("Bảng Điểm", bangDiem);
}//GEN-LAST:event_jbInputDiemActionPerformed

private void jbClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClassActionPerformed
        frmLopHoc lophoc = new frmLopHoc();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Lớp Học", lophoc);
}//GEN-LAST:event_jbClassActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        frmMonHoc monhoc = new frmMonHoc();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Môn Học", monhoc);
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        frmKhoa khoa = new frmKhoa();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Khoa", khoa);
}//GEN-LAST:event_jButton6ActionPerformed

private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
        System.exit(0);
}//GEN-LAST:event_jmiExitActionPerformed

private void jmTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmTimKiemMouseClicked
        Search timkiem = new Search();
        jtpContent.removeAll();
        jtpContent.add("Tìm Kiếm", timkiem);
}//GEN-LAST:event_jmTimKiemMouseClicked

private void jmTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTimKiemActionPerformed
        Search timkiem = new Search();
        jtpContent.removeAll();
        jtpContent.add("Tìm Kiếm", timkiem);
}//GEN-LAST:event_jmTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jbClass;
    private javax.swing.JButton jbInputDiem;
    private javax.swing.JButton jbInputStudent;
    private javax.swing.JButton jbInputTeacher;
    private javax.swing.JMenu jmHeThong;
    private javax.swing.JMenu jmTimKiem;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JTabbedPane jtpContent;
    // End of variables declaration//GEN-END:variables
}
